replicaCount: 1

image:
  repository: t0mx2as0/modulo_form
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000

serviceAccount:
  create: true
  name: sa-cluster-reader

resources:
   requests: 
      memory: "256Mi"
      cpu: "0.5"
   limits:
      memory: "512Mi"
      cpu: "1"

livenessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1