apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp #{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp #{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: webapp #{{ .Release.Name }}
    spec:
      containers:
        - name: webapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000