apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
  namespace: formazione-sou
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: {{ .Release.Name }}